# -*- coding: utf-8 -*-
"""swin_small_ISL_gpu_pt_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/unicreator/swin-small-isl-gpu-pt-1.fa34e9a1-9eef-4cf3-b420-994e497e5bf0.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260405/auto/storage/goog4_request%26X-Goog-Date%3D20260405T120812Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D3cccdf7dfd5b72851c240b2725ec7bb3b1efa47b966214db1f0630c55cc5b6ed8fa62a839dc59b0340a1fa85030aad22f82d7aafe36bb0d233787a13b8542bf28bfcc8db96c5b4729309a0e1daf18d3e6df130f19e0a5bf06ca33c80cd481bbaa2c35eab137a0fb687cf0258e3065f2cff925ff238413bec8a3e017253b4def3c33541d8c841b67f5049f2c7dfb555aee4b55632dddb6b39340c2d292f99af2ed3861c7f314a1f412ad67f03e2757522a2587592f7c87abd6efffa0f315147039665928c1cf7441dad511b47c2f0725c059ff8b8940a50cb5d1fc30c8e94c5d380978521449afb23feca2bc2ccf669035cc1d8f5f8b5fabbf82662c9ed926bdd
"""

import kagglehub
kaushikyh_indian_sign_language_words_with_landmarks_path = kagglehub.dataset_download('kaushikyh/indian-sign-language-words-with-landmarks')

print('Data source import complete.')

"""# Import Libraries"""

!pip uninstall -y tensorflow

import torch
torch.autograd.set_detect_anomaly(True)

print('pytorch version', torch.__version__)
print("GPU available:", torch.cuda.device_count())
#print('GPU name:',torch.cuda.get_device_name(0))

# Set the device (GPU or CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# For Creating Dataloaders
from torch.utils.data import Dataset, DataLoader

# For Vision-ML model
import torchvision
from torchvision import transforms, models
from torchvision.transforms import v2
from torchvision.models import video as ptv

# For Deep Neural Network
import torch.nn.functional as F
from torch.nn import Linear, Softmax, CrossEntropyLoss, ReLU, Flatten, Sequential

!pip install -q decord

# Use PyTorch bridge for Decord
import decord

from decord.bridge import set_bridge
decord.bridge.set_bridge("torch")

from decord import VideoReader

import transformers

# For Tokenizers
from transformers import VivitImageProcessor

# For TPU
from transformers import set_seed
from torch.optim import AdamW
from accelerate import Accelerator, notebook_launcher

# For Display
from tqdm.notebook import tqdm
from torchsummary import summary

# General imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [8,5]

import random
import cv2
import os
import PIL
import gc
from glob import glob
import shutil

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

"""# Initialise Global Constants"""

output_dir = '/kaggle/working'
data_dir = kaushikyh_indian_sign_language_words_with_landmarks_path
image_dir = os.path.join(kaushikyh_indian_sign_language_words_with_landmarks_path, 'ProcessedData_vivit')

BATCH_SIZE = 16
print('BATCH_SIZE =',BATCH_SIZE)

IMAGE_PROCESSOR = 'google/vivit-b-16x2'
WEIGHTS = 'KINETICS400_V1'

CLIP_LENGTH = 32 # MTech project was with CLIP_LENGTH = 85, CLIP_LENGTH of pretrained model = 32
print('Number of Frames =',CLIP_LENGTH)

CLIP_SIZE = 224
print('Image Dimension =', CLIP_SIZE,'X', CLIP_SIZE)

SEED = 42

def seed_everything(seed=42):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

seed_everything(SEED)

"""# Import metadata"""

classes = sorted(os.listdir(image_dir))
print(classes)

label_to_idx = {}
idx_to_label = {}

for idx, label in enumerate(classes):
  class_folder = os.path.join(image_dir, label)
  if os.path.exists(data_dir):
    label_to_idx[label] = idx
    idx_to_label[idx] = label

print(label_to_idx)

print(idx_to_label)

# Collect all video files
video_path = []
labels_int = []
labels_text = []
for idx, label in enumerate(classes):
  class_folder = os.path.join(image_dir, label)
  #print(class_folder)
  video_file = glob(os.path.join(class_folder, '*.MOV'))
  #print(video_file)
  video_path.extend(video_file)
  labels_int.extend([idx] * len(video_file))
  labels_text.extend([label] * len(video_file))

print('input path size:', len(video_path))
print(video_path[:20])

print('labels size:', len(labels_int))
print(labels_int[:20])

print('labels size:', len(labels_text))
print(labels_text[:20])

"""# Train test split"""

train_path, val_path, train_label, val_label = train_test_split(video_path, labels_int, test_size=0.2, stratify=labels_text, random_state=SEED)
train_path, test_path, train_label, test_label = train_test_split(train_path, train_label, test_size=0.2, stratify=train_label, random_state=SEED)

print('Train data size:',len(train_path))
print('Val data size:',len(val_path))
print('Test data size:',len(test_path))

train_label[:5]

"""# Create Dataset"""

image_processor = VivitImageProcessor.from_pretrained(IMAGE_PROCESSOR, attn_implementation="sdpa", torch_dtype=torch.float16)

class CreateDataset(Dataset):
    def __init__(self, clip_length, image_processor, video_paths, labels, training=True):
        super().__init__()
        self.clip_length = clip_length
        self.image_processor = image_processor

        self.video_paths = video_paths
        self.labels = labels
        self.training = training

        # Define a transformation pipeline
        self.transform_train = v2.Compose([
                                    v2.ToImage(),
                                    v2.RandomPerspective(),
                                    v2.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5, hue=0.05),
                                    v2.ToDtype(torch.uint8, scale=False)
                                ])

    def __len__(self):
        return len(self.video_paths)

    def __getitem__(self, idx):

        # Read the Videos and Labels
        vr = VideoReader(self.video_paths[idx])
        label = torch.tensor(self.labels[idx], dtype=torch.long)

        # Process the video
        video = vr.get_batch(list(range(len(vr))))
        video = video[:self.clip_length]
        if self.training:
            # Data Preperation for ML model with Augmentation
            video = self.transform_train(video.permute(0, 3, 1, 2))
        else:
            # Data Preperation for ML Model without Augmentation
            video = v2.functional.to_dtype(video.permute(0, 3, 1, 2), torch.uint8, scale=False)

        # Scaling the video to ML model's desired format
        video = self.image_processor(list(video), return_tensors='pt', input_data_format='channels_first')
        pixel_values = video['pixel_values'].squeeze(0)
        pixel_values = pixel_values.permute(1, 0, 2, 3)

        del vr, video
        gc.collect()

        return {
                'labels': label,
                'pixel_values': pixel_values
                }

train_ds = CreateDataset(clip_length=CLIP_LENGTH,
                         image_processor=image_processor, training=True,
                         video_paths=train_path,
                         labels=train_label
                         )
train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)

val_ds = CreateDataset(clip_length=CLIP_LENGTH,
                         image_processor=image_processor, training=False,
                         video_paths=val_path,
                         labels=val_label
                         )
val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE)

test_ds = CreateDataset(clip_length=CLIP_LENGTH,
                         image_processor=image_processor, training=True,
                         video_paths=test_path,
                         labels=test_label
                         )
test_dl = DataLoader(test_ds, batch_size=BATCH_SIZE)

"""# Testing custome image processing"""

# Convert images to numpy for visualization
def imgshow(img):
    img = img / 2 + 0.5  # Unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

inputs = next(iter(train_dl))
inp_pixel = inputs['pixel_values']
inp_label = inputs['labels']
print('inputs shape: ',inp_pixel.shape, inp_label.shape)
print('label',inp_label[0])
imgshow(torchvision.utils.make_grid(inp_pixel.permute(0, 2, 1, 3, 4)[0]))

inputs = next(iter(val_dl))
inp_pixel = inputs['pixel_values']
inp_label = inputs['labels']
print('inputs shape: ',inp_pixel.shape, inp_label.shape)
print('label',inp_label[0])
imgshow(torchvision.utils.make_grid(inp_pixel.permute(0, 2, 1, 3, 4)[0]))

inputs = next(iter(test_dl))
inp_pixel = inputs['pixel_values']
inp_label = inputs['labels']
print('inputs shape: ',inp_pixel.shape, inp_label.shape)
print('label',inp_label[0])
imgshow(torchvision.utils.make_grid(inp_pixel.permute(0, 2, 1, 3, 4)[0]))

"""# Testing model structure"""

#sample_model_1 = ptv.swin3d_s(weights=WEIGHTS).to(device)

#summary(sample_model_1, (3,32,224,224))

#sample_model_1

## Freeze all layers initially
#for param in sample_model_1.parameters():
#    param.requires_grad = False

#sample_model_1.features[6][1]

## Un-freeze only the last sequential layer
#for param in sample_model_1.features[6][1].parameters():
#    param.requires_grad = True

#summary(sample_model_1, (3,32,224,224))

"""# Model Building"""

hyperparameters = {
    "learning_rate": 0.0001,
    "num_epochs": 1000, # set to very high number
    "seed": SEED,
    "patience": 10, # early stopping
    "output_dir_pt": f"{output_dir}/swin_small_ISL_gpu_pt_1.pt",
    "attention_dropout": 0.2,
    "dropout_rate": 0.2,
    "num_classes": len(classes),
    #"norm_layer": nn.LayerNorm(normalized_shape=torch.Tensor([3])) # normalized_shape =. number of channels
}

from torch import nn
class SwinTClassifications(nn.Module):
    def __init__(self,classes, weights="DEFAULT"):
        super().__init__()
        self.classes = classes
        self.weights = weights
        # Load pre-trained model
        self.base_model = ptv.swin3d_s(weights=self.weights,
                                       #dropout=hyperparameters['dropout_rate'],
                                       #attention_dropout=hyperparameters['attention_dropout'],
                                       #norm_layer=hyperparameters['norm_layer'],
                                       )

        # Update the Classification layer to have 76 classes
        #self.base_model.head = torch.nn.Linear(self.base_model.head.in_features , len(self.classes))
        self.classification_head = nn.Sequential(torch.nn.Linear(self.base_model.head.in_features , len(self.classes)),
                                             #nn.Softmax(dim=1)
                                             )

        # Remove the classification head
        self.base_model.head = nn.Identity()

        ## Enable gradient checkpointing to save memory
        #self.base_model.gradient_checkpointing_enable()

        # Freeze all layers initially
        for param in self.base_model.parameters():
            param.requires_grad = False

        # Un-Freeze the last Sequential layer
        for param in self.base_model.features[6][1].parameters():
            param.requires_grad = True

    def forward(self, x):
        x = self.base_model(x)  # Feature extraction
        x = self.classification_head(x)
        return x  # Return classes

def training_function():
    # Initialize accelerator with fp16 if available
    accelerator = Accelerator() #mixed_precision="fp16"

    # Instantiate the model and config
    embedding_model = SwinTClassifications(classes=classes, weights=WEIGHTS)
    #embedding_model = ptv.swin3d_t(weights=WEIGHTS,
    #                               dropout=hyperparameters['dropout_rate'],
    #                               num_classes=hyperparameters['num_classes'],
    #                               attention_dropout=hyperparameters['attention_dropout'],
    #                               norm_layer=hyperparameters['norm_layer'])

    # Set seed
    set_seed(hyperparameters["seed"])

    # Loss function
    criterion = torch.nn.CrossEntropyLoss()

    # Filter parameters to include only the ones that require gradients
    #trainable_params = [p for p in embedding_model.parameters() if p.requires_grad]
    optimizer = AdamW(embedding_model.parameters(), lr=hyperparameters["learning_rate"])
    #optimizer = AdamW(trainable_params.parameters(), lr=hyperparameters["learning_rate"])

    # Learning rate scheduler
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=0.5, patience=2, min_lr=0.00001
    )

    # Prepare objects with the accelerator
    accelerated_model, accelerated_optimizer, accelerated_criterion, accelerated_train_dl, accelerated_val_dl = accelerator.prepare(
        embedding_model, optimizer, criterion, train_dl, val_dl
    )

    accelerator.print(summary(accelerated_model, ((3, 32, 224, 224))))

    # Training loop variables
    epochs_no_improve = 0
    min_val_loss = float("inf")

    for epoch in range(hyperparameters["num_epochs"]):
        progress_bar = tqdm(range(len(accelerated_train_dl)), disable=not accelerator.is_main_process)
        progress_bar.set_description(f"Epoch: {epoch}")
        accelerated_model.train()
        training_loss = []

        for batch in accelerated_train_dl:
            # Extract inputs
            pixel_value = batch['pixel_values']
            label = batch['labels']

            # Forward pass
            outputs = accelerated_model(pixel_value)

            # Compute loss
            train_loss = accelerated_criterion(outputs, label)

            # Backward pass
            accelerator.backward(train_loss)

            # Optimizer step and gradient reset
            accelerated_optimizer.step()
            accelerated_optimizer.zero_grad()

            # Delete unwanted data
            del pixel_value, outputs, label
            gc.collect()

            # Gather loss from all processes
            training_loss.append(accelerator.gather(train_loss[None]))
            progress_bar.set_postfix({'loss': train_loss.detach().item()})
            progress_bar.update(1)

        # Compute average training loss
        training_loss_final = torch.stack(training_loss).sum().item() / len(training_loss)
        accelerator.print(f"epoch {epoch}: learning rate: {scheduler.get_last_lr()}")
        accelerator.print(f"epoch {epoch}: training loss: {training_loss_final}")

        # Evaluation on validation set
        accelerated_model.eval()
        validation_loss = []
        for batch in accelerated_val_dl:
            # Extract inputs
            pixel_value = batch['pixel_values']
            label = batch['labels']

            with torch.no_grad():
                outputs = accelerated_model(pixel_value)

            # Compute loss
            val_loss = accelerated_criterion(outputs, label)
            validation_loss.append(accelerator.gather(val_loss[None]))

            # Delete unwanted data
            del pixel_value, outputs, label
            gc.collect()

        validation_loss_final = torch.stack(validation_loss).sum().item() / len(validation_loss)
        accelerator.print(f"epoch {epoch}: validation loss: {validation_loss_final}")

        # Update the learning rate scheduler
        scheduler.step(validation_loss_final)

        # Early stopping and model saving
        if validation_loss_final < min_val_loss:
            epochs_no_improve = 0
            min_val_loss = validation_loss_final
            # Save the model weights as state_dict
            torch.save(accelerated_model.state_dict(), hyperparameters['output_dir_pt'])
        else:
            epochs_no_improve += 1
            if epochs_no_improve == hyperparameters["patience"]:
                accelerator.print("Early stopping!")
                break

# Run the trainer function
training_function()

"""# Load Model"""

class SwinTClassifications(nn.Module):
    def __init__(self,classes, weights="DEFAULT"):
        super().__init__()
        self.classes = classes
        self.weights = weights
        # Load pre-trained model
        self.base_model = ptv.swin3d_s(weights=self.weights)

        self.classification_head = nn.Sequential(torch.nn.Linear(self.base_model.head.in_features , len(self.classes)),
                                             #nn.Softmax(dim=1)
                                             )

        # Remove the classification head
        self.base_model.head = nn.Identity()

    def forward(self, x):
        x = self.base_model(x)  # Feature extraction
        x = self.classification_head(x)
        return x  # Return classes

recon_model = SwinTClassifications(classes=classes, weights=WEIGHTS).to(device)
recon_model.load_state_dict(torch.load(hyperparameters['output_dir_pt'], weights_only=True, map_location=device))
recon_model.eval()
print("Entire model loaded successfully!")
print(summary(recon_model, (3, 32, 224, 224)))

"""# Make Predictions"""

# Now we train the model
def testing_function(model_pretrained):
    # Initialize accelerator
    accelerator = Accelerator()#(fp16=True)

    # The seed need to be set before we instantiate the model, as it will determine the random head.
    set_seed(hyperparameters["seed"])

    # There is no specific order to remember, we just need to unpack the objects in the same order we gave them to the
    # prepare method.
    accelerated_model, acclerated_test_dl = accelerator.prepare(model_pretrained, test_dl)

    # Build the training loop
    epochs_no_improve = 0

    # Evaluate at the end of the epoch (distributed evaluation as we have 8 TPU cores)
    accelerated_model.eval()

    test_labels = []
    test_preds = []
    test_outputs = []

    for batch in tqdm(acclerated_test_dl):

        pixel_value = batch['pixel_values']
        test_label = batch['labels']

        with torch.no_grad():
            outputs = accelerated_model(pixel_value)

        test_softmax = torch.nn.functional.softmax(outputs, dim=-1)
        test_pred = test_softmax.argmax(-1)
        test_preds.append(test_pred)

        test_outputs.append(outputs)
        test_labels.append(test_label)

    return test_labels, test_preds, test_outputs

actual_label, predicted_test_label, predicted_test_outputs = testing_function(recon_model)

"""# Analyze predictions"""

actual_labels = torch.cat(actual_label, 0).to('cpu')
predicted_test_labels = torch.cat(predicted_test_label,0).to('cpu')
predicted_test_outputs = torch.cat(predicted_test_outputs).to('cpu')

print('predictions',predicted_test_labels.numpy())

print(actual_labels)

predicted_test_outputs

print(classification_report(actual_labels.numpy(),
                            predicted_test_labels.numpy(),
                            ))

